In [77]:
import numpy as np

# 1.ARRAY DECLARATION AND BASIC CONCEPTS

In [2]:
a=np.array([1,2,3,4],dtype='int16')
print(a)

[1 2 3 4]


In [3]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


### 1.1 ARRAY DIMENSIONS

In [4]:
a.ndim

1

In [5]:
b.ndim

2

### 1.2 FINDING THE SHAPE OF ARRAY

In [6]:
a.shape

(4,)

In [7]:
b.shape

(2, 3)

### 1.3 BASIC CONSEPTS

In [8]:
type(a)

numpy.ndarray

In [9]:
a.dtype

dtype('int16')

In [10]:
a.itemsize

2

In [11]:
a.size

4

In [12]:
a.dtype

dtype('int16')

In [13]:
b.size*b.itemsize

24

# 2. ARRAY SLICING USING INDEX

In [14]:
c=np.array([[1,2,3,4,5,6],[2,8,5,9,3,3]])
print(c)

[[1 2 3 4 5 6]
 [2 8 5 9 3 3]]


In [15]:
c[1,1]

8

In [16]:
c[1][1]

8

In [17]:
c[0][0:]

array([1, 2, 3, 4, 5, 6])

In [18]:
c[0,:]

array([1, 2, 3, 4, 5, 6])

In [19]:
c[0][1:6:2]

array([2, 4, 6])

In [20]:
c[0,1:6:2]

array([2, 4, 6])

In [21]:
c[0][0]=200
print(c)

[[200   2   3   4   5   6]
 [  2   8   5   9   3   3]]


In [22]:
c[:,3]

array([4, 9])

In [23]:
c[:,2]=[1,2]
print(c)

[[200   2   1   4   5   6]
 [  2   8   2   9   3   3]]


In [24]:
d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [25]:
d.shape

(1, 3, 3)

In [26]:
d.ndim

3

In [27]:
d[0,0:1,:]

array([[1, 2, 3]])

# 3. TYPES OF ARRAYS

In [28]:
np.zeros(3)

array([0., 0., 0.])

In [29]:
z1=np.zeros((1,3))
print(z1)

[[0. 0. 0.]]


In [30]:
z1.ndim

2

In [31]:
z2=np.zeros((2,3))
print(z2)

[[0. 0. 0.]
 [0. 0. 0.]]


In [32]:
np.ones((4,2,2),dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [78]:
np.full((3,2),6)

array([[6, 6],
       [6, 6],
       [6, 6]])

### 3.1 ARRAYS USING RANDOM METHOD

In [33]:
np.random.rand(4,2)

array([[0.24985114, 0.54229124],
       [0.11116102, 0.36912902],
       [0.2939684 , 0.96575666],
       [0.3275437 , 0.4823418 ]])

In [34]:
np.random.randint(5,7,size=(3,3))

array([[5, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [35]:
np.random.random((2,2))

array([[0.3554636 , 0.72571677],
       [0.21294647, 0.46764016]])

### 3.2 ARANGE FUNCTION

In [36]:
ar=np.arange(10,20,2)
print(ar)

[10 12 14 16 18]


### 3.3 LINSPACE FUNCTION

In [37]:
ar1=np.linspace(5,6,10)
print(ar1)
print(ar1.dtype)

[5.         5.11111111 5.22222222 5.33333333 5.44444444 5.55555556
 5.66666667 5.77777778 5.88888889 6.        ]
float64


### 3.4 IDENTITY MATRIX

In [38]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 3.5 REPEAT FUNCTION

In [39]:
e=np.array([[1,2,3]])
r1=np.repeat(e,4,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [40]:
outer=np.ones((5,5),dtype='int32')
inner=np.zeros((3,3))
inner[1,1]=9
outer[1:4,1:4]=inner
print(outer)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# 4.COPYING FROM ONE ARRAY TO ANOTHER

In [41]:
f=np.array([1,2,3,4])
g=f.copy()
g[0]=200
print("f[0] : ",f[0])
print("g[0] : ",g[0])




f[0] :  1
g[0] :  200


# 5.MATHEMATICAL OPERATIONS

In [42]:
h=np.array([5,8,10])
h+2

array([ 7, 10, 12])

In [43]:
h*3

array([15, 24, 30])

In [44]:
h/2

array([2.5, 4. , 5. ])

In [45]:
h-3

array([2, 5, 7])

In [46]:
i=np.array([1,0,1])
h+i

array([ 6,  8, 11])

In [48]:
o=np.array([7,3,8,2])
o1=np.array([7,3,4,1])
np.subtract(o,o1)

array([0, 0, 4, 1])

In [49]:
o3=np.divide(o,o1)
o3.astype('int32')

array([1, 1, 2, 2])

In [50]:
np.multiply(o,o1)

array([49,  9, 32,  2])

In [51]:
np.exp(o)

array([1096.63315843,   20.08553692, 2980.95798704,    7.3890561 ])

In [52]:
np.sqrt(o)

array([2.64575131, 1.73205081, 2.82842712, 1.41421356])

In [53]:
np.log(o)

array([1.94591015, 1.09861229, 2.07944154, 0.69314718])

In [54]:
np.sin(h)

array([-0.95892427,  0.98935825, -0.54402111])

In [55]:
np.cos(h)

array([ 0.28366219, -0.14550003, -0.83907153])

### 5.1 MATRIX MULTIPLICATION

In [56]:
j=np.full((2,2),5)
k=np.full((2,2),4)
np.matmul(j,k)

array([[40, 40],
       [40, 40]])

### 5.2 FINDING THE DETERMINANT OF A MATRIX

In [57]:
l=np.identity(3)
np.linalg.det(l)

1.0

### 5.3 BASIC STATISTICAL OPERATIONS

In [58]:
o=np.array([7,3,8,2])
np.min(o)

2

In [59]:
np.max(o)

8

In [60]:
np.mean(o)

5.0

In [61]:
np.median(o)

5.0

In [62]:
np.sum(o)

20

In [69]:
np.std(o)

2.5495097567963922

In [70]:
np.corrcoef(o)

1.0

# 6.ARRAY MANIPULATION

In [63]:
print(o)
p=o.reshape((2,2))
print(p)
q=p.reshape((4,1))
print(q)


[7 3 8 2]
[[7 3]
 [8 2]]
[[7]
 [3]
 [8]
 [2]]


### 6.1 VERTICAL STACKING

In [64]:
v1=np.array([9,7,5])
v2=np.array([4,6,7])

np.vstack((v1,v2,v1,v2))

array([[9, 7, 5],
       [4, 6, 7],
       [9, 7, 5],
       [4, 6, 7]])

### 6.2 HORIZONTAL STACKING

In [65]:
np.hstack((v1,v2))

array([9, 7, 5, 4, 6, 7])

In [66]:
np.hstack((v1,v1,v2))

array([9, 7, 5, 9, 7, 5, 4, 6, 7])

### 6.3 CHECKING IF TWO ARRAYS ARE EQUAL OR NOT

In [68]:
a=[1,2,3]
b=[1,2,4]
print(np.equal(a,b))
print(np.array_equal(a,b))

[ True  True False]
False


### 6.4 ARRAY CONCATENATION

In [76]:
r=np.array([[67,23,90,12]])
s=np.array([[4,5,6,7]])
print(np.concatenate([r,s],axis=0))
print(np.concatenate([r,s],axis=1))

[[67 23 90 12]
 [ 4  5  6  7]]
[[67 23 90 12  4  5  6  7]]
